### ISSUE TITLE
API_INITDATA

### ISSUE THREAD

**Issue by Serjio85** [IgorKonstantinov/CircusClownBot#1]
где взять API_INITDATA ?

**Comment by IgorKonstantinov** [comment]
к сожалению я не нашел где ее взять напрямую, видимо генерируется игрой при старте. Ее можно найти в дебаг режиме
![photo_2024-08-14_20-27-27](https://github.com/user-attachments/assets/bde18fc7-e803-4772-968d-5ef1d83c8aaa)

**Comment by Serjio85** [comment]
Спасибо, пошло
